CREATE TABLE RESULTS (
    ID          SERIAL PRIMARY KEY,
    JOB_ID      INTEGER REFERENCES JOBS(ID),
    RUN_NUM     INTEGER,
    RUN_TIME    TIMESTAMP
)

CREATE TABLE JOBS (
    ID          SERIAL PRIMARY KEY,
    TOPIC       VARCHAR(20),
    FIRST_RUN   TIMESTAMP
)
